apiVersion: v1
kind: ConfigMap
metadata:
  name: hobo-conf
  namespace: hsds
data:
  hobo-connect.conf: >+
    # HOBO configuration

    [HOBO]

    query_endpoint = https://webservice.hobolink.com/ws/data/file/JSON/user

    user_id = 16260

    token_endpoint = https://webservice.hobolink.com/ws/auth/token

    client_id = 

    client_secret = 

    start_date_time = 2022-09-01 00:00:00

    end_date_time = 

    polling_interval_minutes = 1440

    only_new_data = 

    last_successful_query_time =

    max_map_items = 1000000

    max_api_query_items = 99999

    max_api_time_delta_minutes = 1440

    min_api_time_delta_minutes = 5

    request_timeout = 90

    [HSDS]

    hsds_filename = hdf5://projects/nsfarctic/uva-arc-alaska.h5

    hsds_endpoint = http://hsds.pods.uvarc.io

    [META]

    meta_repo = https://gitlab.com/uva-arc/deployment-metadata

    meta_local_dir = /tmp/

    meta_root_path = alaska/uva-arc.yml

    meta_loggers_dir = alaska/loggers

    meta_sensors_dir = alaska/sensors

    
binaryData: {}
